server:
  # consul服务端口
  port: 8007
spring:
  application:
    name: cloud-provider-payment
  cloud:
    consul:
      # consul注册中心地址
      host: localhost
      #consul 默认暴露的注册中心端口是8500
      port: 8500
      # 发现者的地址和服务名称
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}