server:
  port: 3344
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:PeachDream/springcloud-config.git
#          uri: https://github.com/PeachDream/springcloud-config.git
          search-paths:
            - springcloud-config
      label: main  #这里我的是main分支 但是还是要填写master才能够访问