  server:
    port: 8802
  spring:
    application:
      name: cloud-stream-privider
    cloud:
      stream:
#        bindings:
#          send-in-0:
          #同时配置group还可以做持久化的工作 也就是当我们的配置了group之后重启这个消费者它能够从
          #它能够从分组中拿到没有消费的消息并且将其消费了 如果没有配置 重启之后就不会去拿消息
#          group: peachA  #设置消息分组 如果有消费者在同一组内他们就会形成竞争关系
        binders:   #自此处配置要绑定的rabbitmq的服务信息
          defaultRabbit: #表示定义的名称，用于binding整合
            type: rabbit #消息组件类型
            environment:  # 设置rabbitmq的相关的环境配置
              spring:
                rabbitmq:
                  host: localhost
                  port: 5672
                  username: guest
                  password: guest

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:7001/eureka/
    instance:
      lease-expiration-duration-in-seconds: 5 #如果现在超过了5秒的间隔
      lease-renewal-interval-in-seconds: 2 #设置心跳的时间间隔
      instance-id: send-8802.com
      prefer-ip-address: true #访问的路径变为IP地址




