server:
  port: 9527

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: cloud-gateway-service
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_create # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/create/** # 断言，路径相匹配的进行路由
        - id: payment_lb
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
           - Path=/payment/lb/** #断言,路径相匹配的进行路由
        - id: payment_get
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
           - Path=/payment/get/**
           - After=2021-03-10T23:41:18.037+08:00[Asia/Shanghai]
           - Between=2021-03-10T23:41:18.037+08:00[Asia/Shanghai],2021-03-12T12:15:18.037+08:00[Asia/Shanghai]
           - Cookie=username,peach #这里逗号左边是cookie的名称，右边是cookie的值
           - Header=X-request-Id,\d+
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能 利用微服务名进行路由

