server:
  port: 80


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
feign:
  client:
    config:
      CLOUD-PAYMENT-SERVICE: #填写服务名称指代这个服务可以等待的超时时间
#      default:   #默认是代表所有的服务
        connect-timeout: 5000       #建立socket连接的时间  这两个超时参数需要根据实际的程序运行情况来定
        read-timeout: 5000          #读取时间 也就是请求处理的时间

#配置service的日志级别为debug 这个配置和mybatis的一致
logging:
  level:
    com.peach.springcloud.service.PaymentService: debug